//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int NumberOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int PointGet { get; set; }
        public string FCs { get; set; }
        public int CodeGet { get; set; }
        public string Status { get; set; }
        public int Quantity { get; set; }
        public string ArticleProduct { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
